name: API tests router


on: [push]

jobs:
  run-integration-tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Checkout the git branch
        uses: actions/checkout@v2.3.4
        with:
          repository: ngeorgomanolis/workflows
          path: './examples/env/'
          lfs: false
      - run: | 
          ls -lr
          cd examples
          ls -lr
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}