name: API tests router


on:
  pull_request:
    branches: 
      - master
    types: [closed]

jobs:
  get-env:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    name: Get local env from ng-auth repo
    runs-on: ubuntu-20.04
    steps:
      - run: echo "event name is:" ${{ github.event_name }} 
      - run: echo "event type is:" ${{ github.event.action }}
      - run: echo "pull merged is:" ${{ github.event.pull_request.merged }} 
      #- name: Checkout the git branch
      #  uses: actions/checkout@v2.3.4
      #  with:
      #    repository: ngeorgomanolis/workflows
      #   path: './'
      #    lfs: false
      #- name: Listing files/folders
      #  run: ls -lr
      #- name: Upload tests/postman/env/local.json
      #  uses: actions/upload-artifact@v2.2.3
      #  with:
      #    name: local_env
      #    path: examples/env/local.json
      #    if-no-files-found: error
      #   retention-days: 1
  run-integration-tests:
    needs: get-env
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@ngeorgomanolis'
      - name: install newman
        run: npm install -g newman
      - name: Checkout the git branch
        uses: actions/checkout@v2.3.4
        with:
          repository: ngeorgomanolis/workflows
          path: './'
          lfs: false
      - name: copy from workflow branch to main
        run: | 
          pwd
          cp ./examples/env/local.json .
          ls -lr
          echo "github.workspace " ${{ github.workspace }} 
      - name: List folder files
        run:  | 
          ls -lr
          cat local.json
      #- name: Running integration tests
      #  run: |
      #    newman run tests/postman/collection.json -e tests/postman/env/local.json --bail
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}