name: API tests router

on:
  workflow_dispatch:
    inputs:
      chk:
        description: 'Define branch/commit/sha/ref to use as a basis for publishing.'
        required: false

jobs:
  get-env:
    name: Get local env from ng-auth repo
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the git branch
        uses: actions/checkout@v2.3.4
        with:
          repository: ngeorgomanolis/workflows
          path: './'
          lfs: false
      - name: Listing files/folders
        run: ls -lr
      #- uses: actions/setup-node@v2.1.5
      #  with:
      #    node-version: "14.17.3"
      - name: Upload tests/postman/env/local.json
        uses: actions/upload-artifact@v2.2.3
        with:
          name: local_env
          path: ${{ github.workspace }}/examples/env/local.json
          if-no-files-found: error
          retention-days: 1
  run-integration-tests:
    needs: get-env
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@pfizer'
      - name: install newman
        run: npm install -g newman
      - name: Checking out main branch in workflow repository
        uses: actions/checkout@v2
        with:
          repository: ngeorgomanolis/workflows
          path: './'
          token: ${{ secrets.GITHUB_TOKEN }}
          #ref: ${{ github.head_ref }}
      - name: Download local_env
        uses: actions/download-artifact@v2.0.9
        with:
          name: local_env
      - name: List folder files
        run: ls -lr
      #- name: Running integration tests
      #  run: |
      #    newman run tests/postman/collection.json -e tests/postman/env/local.json --bail
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}