name: Publish shared worker

on:
  workflow_dispatch:
    inputs:
      chk:
        description: 'Define branch/commit/sha/ref to use as a basis for publishing.'
        required: false
      tags:
        description: 'New release tag - If given it will override the package.json version field. branch/commit/sha/ref input should be empty.'
        required: false

jobs:
  build:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./evote-api
    permissions: 
      contents: read
      packages: write
    #if: startsWith(github.event.ref, 'refs/tags')
    steps:
      - name: Checking branch...
        if: github.ref != 'refs/heads/master'
        run: |
          echo "You are trying to run the workflow on ${{ github.ref }}; use master instead"
          exit
      - name: Checking out branch/commit/sha/ref
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.chk }}
      - name: Setting up Node env, registry and scope
        uses: actions/setup-node@v2
        with:
          node-version: "14.17.3"
          registry-url: 'https://npm.pkg.github.com'
          scope: '@pfizer'
      - name: Checking Tag input to update package.json version
        if: github.event.inputs.tags != '' && github.event.inputs.chk == ''
        run: |
          echo "Tag: ${{ github.event.inputs.tags }}. Updating package.json..."
          npm version ${{ github.event.inputs.tags }}
      - run: npm build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    

