name: Node.js Package

on:
  workflow_dispatch:
    inputs:
      'branch/commit/sha/ref':
        description: 'Define branch/commit/sha/ref to use as a basis for publishing'     
        required: true
        default: 'master'
      branch:
        description: 'Define branch name'     
        required: true
        default: 'master'
      tags:
        description: 'Release tag'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./evote-api
    permissions: 
      contents: read
      packages: write 
    steps:
      # Runs a single command using the runners shell
      - name: Print branch
        run: echo "Hello ${{ github.event.inputs.branch }}"
      - name: Print tag
        run: echo "Hello ${{ github.event.inputs.tags }}"
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://npm.pkg.github.com'
          # Defaults to the user or organization that owns the workflow file
          scope: '@ngeorgomanolis'
      - run: npm install
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
