name: Node.js Package

on:
  workflow_dispatch:
    inputs:
      #'branch/commit/sha/ref':
      ##  description: 'Define branch/commit/sha/ref to use as a basis for publishing'     
      #  required: true
      #  default: 'master'
      tags:
        description: 'Release tag - It will override the package.json version field'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./evote-api
    permissions: 
      contents: read
      packages: write 
    steps:
      - name: Get tag version from input and update package.json
        if: ${{ github.event.inputs.tags != '' }}
        run: |
          echo "Tags: ${{ github.event.inputs.tags }}" 
          npm version ${{ github.event.inputs.tags }}
        
      # Runs a single command using the runners shell
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://npm.pkg.github.com'
          # Defaults to the user or organization that owns the workflow file
          scope: '@ngeorgomanolis'
      - run: npm install
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
