name: Node.js Package

on:
  workflow_dispatch:
    inputs:
      chk:
        description: 'Define branch/commit/sha/ref to use as a basis for publishing'
      tags:
        description: 'New release tag - If given it will override the package.json version field'

jobs:
  build:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./evote-api
    permissions: 
      contents: read
      packages: write
    #Run the workflow only for master branch otherwise skip 
    #if: github.ref == 'refs/heads/master'
    #run: exit 1
    #if: startsWith(github.event.ref, 'refs/tags')
    steps:
      - name: 'Checking out branch/commit/sha/ref'
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.chk }}
      - name: 'Setting up Node env'
        uses: actions/setup-node@v2
        with:
          node-version: "14.17.3"
          registry-url: 'https://npm.pkg.github.com'
          # Defaults to the user or organization that owns the workflow file
          scope: '@ngeorgomanolis'
      - name: Get tag version from input and update package.json
        if: ${{ github.event.inputs.tags != '' && github.event.inputs.chk == '' }}
        run: |
          echo "Tag: ${{ github.event.inputs.tags }}. Updating package.json..."
          npm version ${{ github.event.inputs.tags }}
      - run: npm build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    

